# Site settings
title: Jekyll-Publisher
email: jekyllpublisher@localhost.com
description: Use Jekyll to build an epub.
baseurl: ""
url: "http://127.0.0.1"

# Build settings
markdown: kramdown

# Exclude things
exclude: [Rakefile]
